Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Pizzerias.urls')),
    path('users/', include('users.urls'))
]

Pizzerias/urls.py
# the path function, which is needed when mapping URLs to views
from django.urls import path

# the dot tells Python to import the views.py module from
# the same directory as the current urls.py module
from . import views

# the variable app_name helps Django distinguish this urls.py file from
# files of the same name in other apps within the project
app_name = 'Pizzerias'

# The variable urlpatterns in this module is a list of individual pages
# that can be requested from the learning_logs app
urlpatterns = [
    # the first argument is an empty string (' ') which matches the
    # base URL - http://localhost:8000/. The second argument specifies 
    # the function name to call in views.py. The third argument provides
    # the name 'index' for this URL pattern to refer to it later
    path('', views.index, name = 'index'),
    path('pizzas', views.pizzas, name = 'pizzas'),
    # the integer value is stored in the variable topic_id and will
    # be subsequently passed to the topic function in views.py
    path('pizzas/<int:pizza_id>/', views.pizza, name = 'pizza'),
    path('new_pizza/', views.new_pizza, name = 'new_pizza'),
    path('new_topping/<int:pizza_id>/', views.new_topping, name = 'new_topping'),
    path('edit_topping/<int:topping_id>/', views.edit_topping, name = 'edit_topping'),
    path('new_comment/<int:pizza_id>/', views.new_comment, name = 'new_comment')

]

users/urls.py
# We import the path function, and then import the include function so we can
# include some default authentication URLs that Django has defined
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name = 'register')
]

Pizzerias/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User

class Pizza(models.Model):
    name = models.CharField(max_length = 200)

    def __str__(self):
        return self.name


class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE)
    name = models.TextField()

    def __str__(self):
        return f"{self.name[:50]}..."

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.text[:50]}..."

Pizzerias/forms.py
from django import forms

from .models import Pizza
from .models import Topping
from .models import Comment

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['name']
        labels = {'name': ''}

class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['name']
        labels = {'name': 'Topping:'}
        # A widget is an HTML form element, such as a single-line text box,
        # a multi-line text area, or drop-down list.
        # customize the input widget for the field 'text' so the text area
        # will be 80 columns wide instead of the default 40
        widgets = {'name': forms.Textarea(attrs={'cols': 80})}

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': 'Comment:'}
        # A widget is an HTML form element, such as a single-line text box,
        # a multi-line text area, or drop-down list.
        # customize the input widget for the field 'text' so the text area
        # will be 80 columns wide instead of the default 40
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
    

Pizzerias/views.py
from django.shortcuts import render, redirect
from .forms import PizzaForm, ToppingForm, CommentForm
from .models import Pizza, Topping, Comment

# Create your views here.

# When a URL requests matches the pattern we just defined,
# Django looks for a function called index() in the views.py file

def index(request):
    """The home page for Pizzeria."""
    return render(request, 'Pizzerias/index.html')

    
def pizzas(request):
    pizzas = Pizza.objects.all()
    # A context is a dictionary in which the keys are names we'll use
    # in the template to access the data, and the values are the data
    # we need to send to the template. In this case, there is one key-value pair,
    # which contains the set of topics we'll display on the page.
    context = {'pizzas':pizzas}
    # When building a page that uses data, we pass the context variable to render()
    # as well as the request object and the path to the template
    return render(request, 'Pizzerias/pizzas.html', context)

def pizza(request, pizza_id):
    # just like we did in MyShell.py
    pizza = Pizza.objects.get(id = pizza_id)
    # foreign key can be accessed using '_set'
    toppings = pizza.topping_set.order_by('name')
    comments = pizza.comment_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings, 'comments': comments}

    return render(request, 'Pizzerias/pizza.html', context)


def new_pizza(request):
    if request.method != 'POST':
        # No data submitted; create a blank form (create an instance of PizzaForm).
        # Because we included no arguments when instantiating PizzaForm, Django
        # creates a blank form that the user can fill out
        form = PizzaForm()
    else:
        # POST data submitted; process data
        # We make an instance of PizzaForm and pass it the data entered by the user,
        # stored in request.POST
        form = PizzaForm(data = request.POST)
        # The is_valid() method checks that all required fields have been filled
        # in (all fields in a form are required by default) and that the data entered
        # matches the field types expected
        if form.is_valid():
            # write the data from the form to the database
            #new_pizza = form.save(commit=False)
            form.save()
            # redirect the user's browser to the pizzas page
            return redirect('Pizzerias:pizzas')

    # Display a blank form using the new_pizza.html template
    context = {'form': form}
    return render(request, 'Pizzerias/new_pizza.html', context)

def new_topping(request, pizza_id):
    pizza = Pizza.objects.get(id = pizza_id)
    if request.method != 'POST':
        form = ToppingForm()
    else:
        form = ToppingForm(data = request.POST)

        if form.is_valid():
            # When we call save(), we include the argument commit=False to tell Django to create
            # a new entry object and assign it to new_entry without saving it to the database yet.
            new_topping = form.save(commit=False)
            # assigns the topic of the new entry based on the topic we pulled from topic_id
            new_topping.pizza = pizza
            new_topping.save()
            form.save()
            return redirect('Pizzerias:pizza', pizza_id = pizza_id)

    context = {'form': form, 'pizza': pizza}
    return render(request, 'Pizzerias/new_topping.html', context)


def edit_topping(request, topping_id):
    """Edit an existing topping."""
    topping = Topping.objects.get(id=topping_id)
    pizza = topping.pizza

    if request.method != 'POST':
        # This argument tells Django to create the form prefilled
        # with information from the existing entry object
        form = ToppingForm(instance = topping)
    else:
        # POST data submitted; process data
        form = ToppingForm(instance = topping, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('Pizzerias:pizza', pizza_id = pizza.id)

    context = {'topping': topping, 'pizza': pizza, 'form': form}
    return render(request, 'Pizzerias/edit_topping.html', context)


def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id = pizza_id)
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data = request.POST)

        if form.is_valid():
            # When we call save(), we include the argument commit=False to tell Django to create
            # a new entry object and assign it to new_entry without saving it to the database yet.
            new_comment = form.save(commit=False)
            # assigns the topic of the new entry based on the topic we pulled from topic_id
            new_comment.pizza = pizza
            new_comment.save()
            form.save()
            return redirect('Pizzerias:pizza', pizza_id = pizza_id)

    context = {'form': form, 'pizza': pizza}
    return render(request, 'Pizzerias/new_comment.html', context)

Pizzerias/templates/Pizzerias/base.html
<p>
    <a href="{% url 'Pizzerias:index' %}">Pizzeria</a>
    <a href="{% url 'Pizzerias:pizzas' %}">Pizzas</a>
    {% if user.is_authenticated %}
        Hello, {{ user.username }}
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a>
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
    </p>
    
    {% block content %}
    
    {% endblock content %}

Pizzerias/templates/Pizzerias/edit_topping.html
{% extends "Pizzerias/base.html" %}

    {% block content %}

    <p><a href="{% url 'Pizzerias:pizza' pizza.id %}">{{ pizza }}</a></p>

    <p>Edit topping:</p>

    <form action="{%url 'Pizzerias:edit_topping' topping.id %}" method = 'post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name = "submit">Save changes</button>
    </form>

{% endblock content %}
    

Pizzerias/templates/Pizzerias/index.html
{% extends "Pizzerias/base.html" %}

{% block content %}
    <h1>Local Pizzeria</h1>
    <p>Welcome to Local Pizzeria</p>
    <p>
        Pizzeria shows different pizzas and their various toppings for 
        which customers can purchase.
    <p>
{% endblock content %}

Pizzerias/templates/Pizzerias/new_comment.html
{% extends "Pizzerias/base.html" %}

    {% block content %}

    <!-- includes the topic_id value in the URL, so the view function can associate the new entry
        with the correct topic-->
    <p><a href="{% url 'Pizzerias:pizza' pizza.id %}">{{ pizza }}</a>
    </p>

        <p>Add a new comment:</p>
    
    <form action="{% url 'Pizzerias:new_comment' pizza.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">Add comment</button>
    </form>

{% endblock content %}

Pizzerias/templates/Pizzerias/new_pizza.html
{% extends "Pizzerias/base.html" %}

    {% block content %}
        <p>Add a new pizza:</p>


        <!-- define an HTML form. The action argument tells the browser where
            to send the data submitted in the form-->
    <form action="{% url 'Pizzerias:new_pizza' %}" method='post'>

        <!-- Django uses the template tag {% csrf_token %} to prevent attackers
            from using the form to gain unauthorized access to the server-->
        {% csrf_token %}

        <!-- We only need to include the template variable {{form.as_p }} for
            Django to create all the fields necessary to display the form automatically.
            The as_p modifier tells Django to render all the form elements in paragraph format,
            as a simple way to display the form neatly.-->
        {{ form.as_p }}

        <!-- create a submit button-->
        <button name="submit">Add pizza</button>
    </form>

    {% endblock content %}

Pizzerias/templates/Pizzerias/new_topping.html
{% extends "Pizzerias/base.html" %}

    {% block content %}

    <!-- includes the pizza_id value in the URL, so the view function can associate the new topping
        with the correct pizza-->
    <p><a href="{% url 'Pizzerias:pizza' pizza.id %}">{{ pizza }}</a>
    </p>

        <p>Add a new topping:</p>
    
    <form action="{% url 'Pizzerias:new_topping' pizza.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">Add topping</button>
    </form>

{% endblock content %}

Pizzerias/templates/Pizzerias/pizza.html
{% extends "Pizzerias/base.html" %}

{% block content %}

    <p>Topic: {{ pizza }}</p>

    <ul>

        {% for topping in toppings %}
        <li>
            <!-- The filter linebreaks ensures that long text entries include line breaks -->
            <p>{{ topping.name|linebreaks }} </p>
            <p>
                <a href="{% url 'Pizzerias:edit_topping' topping.id %}">Edit topping</a>
            </p>
        </li>
        {% empty %} <!-- if the list is empty then display message -->
            <li>There are no toppings for this pizza.</li>
            {% endfor %}
    </ul>

    <p>
        <a href="{% url 'Pizzerias:new_topping' pizza.id %}">Add a new topping</a>
    </p>

    <ul>

        {% for comment in comments %}
        <li>
            <!-- a vertical line (|) represents a template filter
            -a function that modifies the value in a template variable -->
            <p>{{ comment.date_added|date:'M d, Y H:i' }} </p>
            <!-- The filter linebreaks ensures that long text entries include line breaks -->
            <p>{{ comment.text|linebreaks }} </p>
        </li>
        {% empty %} <!-- if the list is empty then display message -->
            <li>There are no comments for this pizza.</li>
            {% endfor %}
    </ul>

    <p>
        <a href="{% url 'Pizzerias:new_comment' pizza.id %}">Add a new comment</a>
    </p>

{% endblock content %}

Pizzerias/templates/Pizzerias/pizzas.html
{% block content %}

<p>Pizzas</p>

<!-- In standard HTMl, a bulleted list is called an unordered list
    and is indicated by the tags <ul></ul>. -->

<ul>
    <!-- for loop to loop through each topic
        NOTE: not like python, needs an endfor -->
    {% for pizza in pizzas %}

    <!-- To print a variable in a template, wrap the
        variable name in double braces -->
    <li>
        <a href ="{% url 'Pizzerias:pizza' pizza.id %}">{{ pizza }}</a>
    </li> <!-- li - list item -->
    {% empty %} <!-- if the list is empty, then display message -->
        <li>No pizzas have been added yet.</li>
    {% endfor %}
</ul>

<a href="{% url 'Pizzerias:new_pizza' %}">Add a new pizza</a>

{% endblock content %}